### ISSUE TITLE
requesting invalid module version 1.4.0-beta

### ISSUE THREAD

**Issue by 7dpk** [microsoft/minecraft-scripting-samples#26]
I was trying to run the `ts-starter`, I've followed each step correctly and as it is. but i'm getting this error in the content log history

```
[Scripting][error]-Plugin [Cotta Behavior Pack] - module [Cotta Behavior Pack - 0.0.1] requesting invalid module version [@minecraft/server - 1.4.0-beta].
Available versions:
@minecraft/server - 0.1.0
@minecraft/server - 1.0.0
@minecraft/server - 1.1.0
@minecraft/server - 1.2.0
@minecraft/server - 1.3.0-beta
```

My mincraft version is 1.20

**Comment by mammerla** [comment]
Those samples last targeted 1.4.0-beta which is associated with the current Minecraft Preview 1.20.10 versions; you may need to tweak the beta version as well.  Soon I think a number of these samples will just move over to stable versions, so there will be less ambiguity about preview vs. stable.

**Comment by 7dpk** [comment]
Thank you!

**Comment by XYZ-99** [comment]
Hi, my Minecraft version is 1.20.1. I followed each step in `ts-starter`, but nothing popped up when I entered my `Cotta Test` world. May I kindly ask:

1. How did you solve the problem at last?
2. What do you refer to as "the content log history"? Because I am not aware of any output file.

Thank you!

**Comment by 7dpk** [comment]
1.3.0-beta

And you can enable content log in Minecraft settings, it'll show you logs of all the executions and errors. Let me know if you are still facing some issues 👍
