### ISSUE TITLE
source location

### ISSUE THREAD

**Issue by weagle08** [microsoft/minecraft-scripting-samples#28]
Is the scripting API open source? If so where is it's location? can MR be created? assuming they are just N-API or NAN wrappers of the underlying c/c++ implementation?

**Comment by MDxWARRIORxOP** [comment]
I dont think that the Scription API is open-source, but ive heard they use a quick-js based engine for it.

More info: https://wiki.bedrock.dev/scripting/api-environment.html

**Comment by mammerla** [comment]
Yes, the QuickJS script engine is used for scripting and there is a binding layer
