### ISSUE TITLE
Block and BlockEvent samples rely on removed withState

### ISSUE THREAD

**Issue by abrightmoore** [microsoft/minecraft-scripting-samples#33]
Block permutations.withState() has been removed in server 1.4.0 and 1.5.0, returning in 1.6.0-beta according to the server change log.

Because of this, the two Block sample scripts are not using stable available APIs compatible with latest retail client 1.20.30 due to their reliance on setting blockstates with withState()

**Comment by mammerla** [comment]
Should now be fixed.
